import {firm,values} from '../data.mjs';
import {image,imageCredit} from '../imagery.mjs';
import {icon} from '../icons.mjs';
import {button,eyebrow,practiceCards,attorneyCards,cta,reviewNote} from '../components.mjs';
export function home(){return `
<section class="hero">${image('office',{className:'hero-image',priority:true})}<div class="hero-shade"></div><div class="shell hero-inner"><div class="hero-copy">${eyebrow('Oviedo Law Group · California')}<h1>When your career<br>and rights are<br><em>on the line.</em></h1><p>Clear counsel for consequential moments.<br>A considered approach to protecting what matters.</p><div class="hero-actions">${button('Speak with the office','/contact/')}<a class="hero-secondary" href="/practice-areas/">Explore our practice ${icon('arrow')}</a></div><div class="hero-principles"><span></span> PEOPLE &nbsp; / &nbsp; PURPOSE &nbsp; / &nbsp; PERSPECTIVE</div></div></div>${imageCredit('office')}</section>
<section class="intro-strip"><div class="shell intro-strip-inner"><p>A focused practice.<br><strong>A personal responsibility.</strong></p><p>For the people who serve. For the work that matters. A clearer way to connect with Oviedo Law Group.</p><a class="text-link" href="/about/">Get to know the firm ${icon('diagonal')}</a></div></section>
<section class="section shell" id="practice"><div class="section-heading"><div>${eyebrow('01 / The practice')}<h2>Serious matters.<br><em>Considered representation.</em></h2></div><p>Find a clear starting point.<br>Talk with the office about your situation.</p></div>${practiceCards()}${reviewNote()}</section>
<section class="attorneys-section"><div class="shell attorney-home-grid"><div class="attorney-intro">${eyebrow('02 / Our attorneys')}<h2>The people<br>behind<br><em>your counsel.</em></h2><span class="accent-rule"></span><p>Representation begins with a relationship. Get to know the attorneys behind Oviedo Law Group.</p>${button('Meet our attorneys','/attorneys/','outline')}</div>${attorneyCards()}</div></section>
<section class="values-section values-section--photo">${image('valley',{className:'section-media',decorative:true})}<div class="shell"><div class="values-heading">${eyebrow('03 / A considered approach')}<h2>Direct counsel.<br><em>Clarity when it matters.</em></h2></div><div class="values-grid">${values.map(v=>`<article>${icon(v.icon)}<h3>${v.title}</h3><p>${v.copy}</p></article>`).join('')}</div></div>${imageCredit('valley')}</section>
<section class="local-section shell"><div class="local-label">${eyebrow('Based in Clovis')}<span class="local-coordinates">CENTRAL VALLEY<br>CALIFORNIA</span></div><div><h2>A local foundation.<br><em>A California perspective.</em></h2><p>A new presentation for an established identity: thoughtful, grounded, and focused on the people who turn to the firm.</p><a class="text-link" href="/contact/">Find the Clovis office ${icon('arrow')}</a></div><div class="location-card">${icon('pin')}<p>${firm.street}<br>${firm.city}</p><span>PUBLICLY LISTED ADDRESS · REVIEW PENDING</span></div></section>
${cta()}`;}
