import {eyebrow,subhero} from '../components.mjs';
export const review=()=>`${subhero('Kodaxa / design review','Same firm.<br><em>A more current presence.</em>','A visual and functional concept—not an authorized replacement for the firm’s existing website.')}
<section class="section shell review-layout"><article>
<div class="review-heading">${eyebrow('What this preview demonstrates')}<h2>A working direction.<br><em>Not a finished claim.</em></h2></div>
<p class="lead">The navy, ivory, serif typography, and restrained burgundy accents translate the supplied mockups into a responsive, multi-page website.</p>
<h3>Images are design references.</h3>
<p>The mockups below contain placeholder portraits and draft copy. The inner-page mockup incorrectly names J.R. Oviedo’s law school; the existing firm biography names McGeorge. The implementation does not reuse those portraits or that incorrect credential.</p>
<h3>Photography and artwork</h3>
<p>The office, meeting room, civic architecture, and dusk landscape establish the visual direction. They are not photographs of the firm’s premises or verified locations. Final imagery and genuine attorney photographs remain subject to approval.</p>
<h3>What still needs the firm’s approval</h3>
<ul class="review-list"><li>Current attorneys, roles, biographies, admissions, and actual portraits.</li><li>Current practice areas and the matters the firm wants to accept.</li><li>Office addresses, hours, phone handling, and Sacramento office status.</li><li>Intake workflow, privacy language, legal notices, accessibility review, and image permissions.</li></ul>
<h3>What this build deliberately does not do</h3>
<p>No invented testimonials, awards, outcomes, case results, or promises. No free-consultation or 24-hour availability claim. No analytics, map embed, cookies, case intake, or public search indexing. A noindex directive is not access control; use hosting-level protection for a private review.</p>
</article><aside class="review-summary"><span class="preview-pill">REVIEW BUILD</span><h3>Prepared by Kodaxa</h3><p>For a conversation about the next chapter of Oviedo Law Group’s online presence.</p><dl><div><dt>Visual direction</dt><dd>Navy · ivory · burgundy</dd></div><div><dt>Status</dt><dd>Independent concept</dd></div><div><dt>Intake</dt><dd>Disabled</dd></div><div><dt>Indexing</dt><dd>Noindex / nofollow</dd></div></dl></aside></section>
<section class="section shell mockups-section">${eyebrow('Original visual direction / optimized reference copies')}<h2>The supplied<br><em>design studies.</em></h2><p>Reference artwork only. Do not use the faces or embedded credentials as factual content.</p><div class="mockup-grid"><figure><a href="/images/homepage-concept.avif"><img src="/images/homepage-concept.avif" width="480" height="864" alt="Homepage layout study with placeholder portraits and draft copy" loading="lazy"></a><figcaption>01 / Homepage direction</figcaption></figure><figure><a href="/images/attorneys-concept.avif"><img src="/images/attorneys-concept.avif" width="480" height="864" alt="Attorney-page layout study with placeholder portraits and draft credentials" loading="lazy"></a><figcaption>02 / Attorney-page direction</figcaption></figure></div></section>`;
