import {firm, practices, attorneys} from './data.mjs';
import {icon} from './icons.mjs';
export const e=(text)=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const button=(text,href,kind='primary')=>`<a class="button button--${kind}" href="${e(href)}">${e(text)}${icon('arrow')}</a>`;
export const eyebrow=(text)=>`<p class="eyebrow">${e(text)}</p>`;
export const navItems=[['The practice','/practice-areas/'],['Our attorneys','/attorneys/'],['The firm','/about/'],['Contact','/contact/']];
export const wordmark=()=>`<a class="wordmark" href="/" aria-label="Oviedo Law Group home"><span>Oviedo <span class="wordmark-light">Law Group</span></span><small>CLOVIS, CALIFORNIA</small></a>`;
const nav=(path)=>navItems.map(([label,url])=>`<a href="${url}"${path.startsWith(url)?' aria-current="page"':''}>${label}</a>`).join('');
export function layout({title,description,path,body}){
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} | OLG design concept</title><meta name="description" content="${e(description)}"><meta name="robots" content="noindex, nofollow, noarchive"><meta name="theme-color" content="#132932"><meta property="og:type" content="website"><meta property="og:title" content="${e(title)} — design concept"><meta property="og:description" content="Independent Kodaxa design preview. Not the firm’s live website."><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles/base.css"><link rel="stylesheet" href="/styles/components.css"><link rel="stylesheet" href="/styles/pages.css"><link rel="stylesheet" href="/styles/responsive.css"><script src="/app.js" defer></script></head><body>
 <a class="skip-link" href="#main">Skip to content</a>
 <aside class="concept-banner" aria-label="Preview notice"><span><strong>DESIGN CONCEPT</strong><span class="concept-extra"> &nbsp; / &nbsp; Prepared by Kodaxa. Not the firm’s live website.</span></span><a href="/design-review/">Review notes ${icon('diagonal')}</a></aside>
 <div class="utility-bar"><div class="shell utility-inner"><span>${icon('pin')} Clovis, California</span><a href="tel:${firm.tel}">${icon('phone')} ${firm.phone}</a><span class="utility-end">A California practice. A personal approach.</span></div></div>
 <header class="header"><div class="shell header-inner">${wordmark()}<nav class="desktop-nav" aria-label="Main navigation">${nav(path)}</nav><a class="header-phone" href="tel:${firm.tel}">${icon('phone')}<span>Call the office</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-menu"><span class="menu-label">Menu</span><span class="menu-lines" aria-hidden="true"></span></button></div><nav class="mobile-nav" id="mobile-menu" aria-label="Mobile navigation" hidden>${nav(path)}</nav></header>
 <main id="main" tabindex="-1">${body}</main>
 <footer class="footer"><div class="shell"><div class="footer-main"><div>${wordmark()}<p class="footer-tagline">Direct counsel.<br>Considered representation.</p></div><div class="footer-address">${eyebrow('The Clovis office')}<address>${e(firm.street)}<br>${e(firm.city)}</address><a class="footer-tel" href="tel:${firm.tel}">${firm.phone} ${icon('diagonal')}</a></div><nav class="footer-nav" aria-label="Footer navigation">${navItems.map(([t,u])=>`<a href="${u}">${t}</a>`).join('')}<a href="/design-review/">About this concept</a></nav></div><div class="footer-legal"><p>Independent design concept by Kodaxa · ${new Date().getUTCFullYear()}</p><p>Not legal advice. Viewing this concept does not establish an attorney-client relationship. No case inquiries are collected here.</p></div></div></footer>
 </body></html>`;
}
export const practiceCards=()=>`<div class="practice-grid">${practices.map(p=>`<a class="practice-card" href="/practice-areas/${p.slug}/"><div class="practice-top">${icon(p.icon)}<span>${p.number}</span></div><h3>${e(p.title)}</h3><p>${e(p.short)}</p><span class="text-link">Explore this area ${icon('arrow')}</span></a>`).join('')}</div>`;
export const portrait=(a)=>`<div class="portrait portrait--${a.slug}" role="img" aria-label="${e(a.name)}: approved portrait not yet supplied"><span class="portrait-rule"></span><span class="portrait-monogram" aria-hidden="true">${a.initials}</span><span class="portrait-caption">APPROVED PORTRAIT TO FOLLOW</span><span class="portrait-corner" aria-hidden="true">OLG</span></div>`;
export const attorneyCards=()=>attorneys.map(a=>`<article class="attorney-card"><a href="/attorneys/${a.slug}/" aria-label="View ${e(a.name)} profile">${portrait(a)}</a><div class="attorney-caption">${eyebrow(a.role)}<h3><a href="/attorneys/${a.slug}/">${e(a.name)}</a></h3><p>${e(a.intro)}</p><a class="text-link" href="/attorneys/${a.slug}/">View profile ${icon('arrow')}</a></div></article>`).join('');
export const cta=()=>`<section class="contact-band"><div class="shell contact-band-inner"><div>${eyebrow('A conversation is the first step')}<h2>Let’s talk about<br><em>what comes next.</em></h2></div><div><p>A direct conversation with the office can help you understand where to begin.</p>${button('Contact the office','/contact/')}</div></div></section>`;
export const subhero=(label,title,description)=>`<section class="subhero"><div class="shell"><a class="breadcrumb" href="/">Home ${icon('arrow')}</a>${eyebrow(label)}<h1>${title}</h1><p class="subhero-copy">${e(description)}</p></div><span class="subhero-mark" aria-hidden="true">OLG</span></section>`;
export const reviewNote=(text='Proposed practice structure. Current services and case acceptance require firm confirmation.')=>`<p class="review-note">${icon('document')}<span>${e(text)}</span></p>`;
